WebBH/WebBH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sanpham.urls', 'home'), namespace='home')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('home/cart/', include(('donhangs.urls', 'donhangs'), namespace='donhangs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

WebBH/donhangs/urls.py
from django.urls import path

from . import views
app_name = 'donhangs'
urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('doanhthu/', views.doanhthu, name='doanhthu'),
    
    path('add/<id>', views.add_cart, name='add_cart'),
    path('addnum/<id>', views.add_cart_num, name='add_cart_num'),

    path('update/<list_id>', views.update_cart, name='update_cart'),
    path('remove/<id>', views.remove_cart, name='remove_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
    path('history/', views.history, name='history'),
    path('history/detail/<id>', views.chitiet, name='chitiet'),

    path('thanhtoan/<id_donhang>',views.thanhtoan,name = 'thanhtoan')
]

WebBH/sanpham/urls.py
from django.urls import path

from . import views
app_name = 'sanpham'
urlpatterns = [
    path('', views.home, name='home'),
    path('branch/<id>', views.list_branch, name='list_branch'),
    path('branch/<id>/product', views.list_branch_product, name='list_branch_product'),
    path('shop/', views.shop_page, name='shop_page'),
    path('shop/search', views.search, name='search'),
    
    
    path('shop/<id>', views.detail_product, name='detail_product'),
    path('shop/<id>/review', views.add_review, name='add_review'),
    path('shop/<id_sp>/vote', views.vote_rating, name='vote_rating'),


    path('category/', views.category, name='category'),
    path('category/<id>', views.list_category, name='list_category'),
    
    path('category/<id>/product', views.list_category_product, name='list_category_product'),

]

WebBH/user/urls.py
from unicodedata import name
from django.urls import path, include

from . import views
app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/',views.signup, name = 'signup'),
    path('profile/<id>',views.update_profile ,name='profile'),
    path('profile/<id>/password',views.update_password ,name='password'),
    path('profile/image_upload/', views.avatarView , name = 'avatarView'),
]

WebBH/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>eElectronics</title>

    <!-- Google Fonts -->
    <link
      href="http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="http://fonts.googleapis.com/css?family=Raleway:400,100"
      rel="stylesheet"
      type="text/css"
    />

    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    />

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
    />

    <!-- Custom CSS -->
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/responsive.css' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'fusioncharts/fusioncharts.js' %}"> </script>
    <script src="{% static 'fusioncharts/fusioncharts.charts.js' %}"></script>
    <script src="{% static 'fusioncharts/themes/fusioncharts.theme.fusion.js' %}"></script>
  </head>
  <body>
    <div class="header-area">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="user-menu">
              <ul>
                <li>
                  {% if request.session.hoten %}
                   <a href="{% url 'user:profile' request.session.id_user %}"><i class="fa fa-user"></i> 
                    {{request.session.hoten}} </a>
                    {% else %}
                   <a ><i class="fa fa-user"></i> 

                    User
                    {% endif %}
                </li>
                <!-- <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li> -->
                <li>
                  <a href="{% url 'donhangs:view_cart' %}"><i class="fa fa-cart-arrow-down"></i> Giỏ hàng </a>
                </li>
                <li>
                  {% if request.session.id_user %}
                <li>
                  <a href="{% url 'donhangs:history' %}"><i class="fa fa-user"></i>Lịch sử giao dịch </a>
                </li>
                {% endif %}
                <li>
                  {% if request.session.id_user %}
                  <a href="{% url 'user:logout' %}"><i class="fa fa-sign-out"></i> Đăng xuất </a>
                  {% else %}
                  <a href="{% url 'user:login' %}"><i class="fa fa-sign-in"></i> Đăng nhập </a>
                  {% endif %}
                </li>


                {% if not request.session.id_user %}
                <li>    
                  <a href="{% url 'user:signup' %}"><i class="fa fa-user-plus"></i> Đăng kí </a>
                </li>
                {% endif %}
                {% if  request.session.quyen %}
                <li>    
                  <a href="{% url 'donhangs:doanhthu' %}"><i class="fa fa-user-plus"></i> Doanhthu </a>
                </li>
                {% endif %}
                

              </ul>
            </div>
          </div>

          <!-- <div class="col-md-4">
            <div class="header-right">
              <ul class="list-unstyled list-inline">
                <li class="dropdown dropdown-small">
                  <a
                    data-toggle="dropdown"
                    data-hover="dropdown"
                    class="dropdown-toggle"
                    href="#"
                    ><span class="key">currency :</span
                    ><span class="value">USD </span><b class="caret"></b
                  ></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">USD</a></li>
                    <li><a href="#">INR</a></li>
                    <li><a href="#">GBP</a></li>
                  </ul>
                </li>

                <li class="dropdown dropdown-small">
                  <a
                    data-toggle="dropdown"
                    data-hover="dropdown"
                    class="dropdown-toggle"
                    href="#"
                    ><span class="key">language :</span
                    ><span class="value">English </span><b class="caret"></b
                  ></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">English</a></li>
                    <li><a href="#">French</a></li>
                    <li><a href="#">German</a></li>
                  </ul>
                </li>
              </ul>
            </div> -->
          </div>
        </div>
      </div>
    </div>
    <!-- End header area -->

    <div class="site-branding-area">
      <div class="container">
        <div class="row">
          <div class="col-sm-4">
            <div class="logo">
              <h1>
                <a href="{% url 'sanpham:home' %}">e<span>Electronics</span></a>
              </h1>
            </div>
          </div>
          <div  class="col-sm-4" style="margin-top:40px" >
            <form action="{% url 'sanpham:search'%}" method="post">
                {% csrf_token %} {{form}}
              <div>
                <input name="noidung" type="text" placeholder="Tìm kiếm ..." style="width:100%;margin-left:30px;" ><button style="position:absolute; right: 0%;top:25%; border: none;background-color: transparent;"><i class="fa fa-search" ></i> </button>
              </div>
            </form>
          </div>
          <div class="col-sm-3">
            
            <div class="shopping-item">
              <a style="margin-left: 15px;" href="{% url 'donhangs:view_cart' %}"
                >Giỏ hàng <i class="fa fa-shopping-cart"></i>
                <!-- <span class="product-count">0</span> -->
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End site branding area -->

    
    <!-- End mainmenu area -->

    {% block contentblock %}
    {% endblock %}
    
    <!-- End product widget area -->

    <div class="footer-top-area">
      <div class="zigzag-bottom"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <div class="footer-about-us">
              <h2>e<span>Electronics</span></h2>
              <p>
                Của hàng bán chạy nhất Đông Nam Á với các sản phẩm mới nhất hiện nay trên toàn thế giới.
              </p>
              <div class="footer-social">
                <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                <a href="#" target="_blank"><i class="fa fa-pinterest"></i></a>
              </div>
            </div>
          </div>

          <!-- <div class="col-md-3 col-sm-6">
            <div class="footer-menu">
              <h2 class="footer-wid-title">User Navigation</h2>
              <ul>
                <li><a href="#">My account</a></li>
                <li><a href="#">Order history</a></li>
                <li><a href="#">Wishlist</a></li>
                <li><a href="#">Vendor contact</a></li>
                <li><a href="#">Front page</a></li>
              </ul>
            </div>
          </div> -->

          <!-- <div class="col-md-3 col-sm-6">
            <div class="footer-menu">
              <h2 class="footer-wid-title">Thể loại</h2>
              <ul>
                <li><a href="#">Mobile Phone</a></li>
                <li><a href="#">Home accesseries</a></li>
                <li><a href="#">LED TV</a></li>
                <li><a href="#">Computer</a></li>
                <li><a href="#">Gadets</a></li>
              </ul>
            </div>
          </div> -->

          <div class="col-md-3 col-sm-6"  style="display:float;float:right">
            <div class="footer-newsletter">
              <h2 class="footer-wid-title">Thư mời</h2>
              <p>
                Đăng ký nhận bản tin của chúng tôi và nhận các ưu đãi độc quyền mà bạn sẽ không tìm thấy ở bất kỳ nơi nào khác ngay trong hộp thư đến của bạn!
              </p>
              <div class="newsletter-form">
                <form action="#">
                  <input type="email" placeholder="Email" />
                  <input type="submit" value="Đăng kí" />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End footer top area -->

    <div class="footer-bottom-area">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="copyright">
              <p>
                &copy; 2022 eElectronics
                <i class="fa fa-heart"></i> 
                <!-- <a href="http://wpexpand.com" target="_blank">WP Expand</a> -->
              </p>
            </div>
          </div>

          <div class="col-md-4">
            <div class="footer-card-icon">
              <i class="fa fa-cc-discover"></i>
              <i class="fa fa-cc-mastercard"></i>
              <i class="fa fa-cc-paypal"></i>
              <i class="fa fa-cc-visa"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End footer bottom area -->

    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>

    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>

    <!-- Main Script -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/select.js' %}"></script>

    
  
  </body>
</html>

WebBH/templates/store/category_product.html
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
{% extends 'store/base.html'%} {% load static %} {% load humanize %} {%block contentblock%}
<div class="mainmenu-area">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'sanpham:home' %}">Home</a></li>
          <li>
            <a href="{% url 'sanpham:shop_page' %}">Sản phẩm</a>
          </li>
          <!-- <li><a href="single-product.html">Single product</a></li> -->
          <li class="active">
            <a href="{% url 'sanpham:category' %}">Thể loại</a>
          </li>

          <!-- <li><a href="#">Others</a></li> -->
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- End mainmenu area -->

<div class="product-big-title-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="product-bit-title text-center">
          <h2>Thể loại</h2>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="single-product-area">
  <div class="zigzag-bottom"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="left-sidebar">
          <h2>Thể loại</h2>
          <div class="panel-group category-products" id="accordian">
            <!--category-list-->
            {% for item in list_category%}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a href="{% url 'sanpham:list_category_product' item.id_loaisanpham %}"> {{item.tenloaisanpham}} </a>
                </h4>
              </div>
            </div>
            {% endfor%}
          </div>
          <!--/category-products-->

          <div class="brands_products">
            <!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
              <ul class="nav nav-pills nav-stacked">
                {% for i in list_branch%}
                <li>
                  <a href="{% url 'sanpham:list_branch_product' i.id_hang %}">
                    <span class="pull-right">({{i.dem}})</span>{{i.tenhang}}</a
                  >
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <!--/brands_products-->
        </div>
      </div>

      <div class="col-md-9">
        <div class="product-content-right">
          <!-- List sp ở đây -->
          <div class="row">
            {% for item in list_sp %}
            <div class="col-md-3 col-sm-6">
              <div class="single-shop-product" style="position: relative; height: 400px">
                <div class="product-upper" style="height: 270px; position: relative">
                  <img
                    src="{% static item.hinhanh %}"
                    alt=""
                    style="position: absolute; top: 50%; transform: translateY(-50%)"
                  />
                </div>
                <h2>
                  <a href="{% url 'sanpham:detail_product' item.id_sanpham %}">{{item.tensanpham}}</a>
                </h2>
                <div class="product-carousel-price" style="position: absolute; bottom: 12%">
                  <ins>{{item.dongia|intcomma}}VNĐ</ins>
                  <!-- <del>$999.00</del> -->
                </div>

                <div class="product-option-shop" style="position: absolute; bottom: 0%">
                  <a
                    class="add_to_cart_button"
                    data-quantity="1"
                    data-product_sku=""
                    data-product_id="70"
                    rel="nofollow"
                    href="{% url 'donhangs:add_cart' item.id_sanpham %}"
                    >Add to cart</a
                  >
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="product-pagination text-center">
                <nav>
                  <ul class="pagination">
                    {% if list_sp.has_previous %}
                    <li>
                      <a href="?page={{ list_sp.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li><a href="?page={{ list_sp.previous_page_number }}">{{ list_sp.previous_page_number }}</a></li>

                    {% endif %}
                    <li><a href="?page={{ list_sp.number }}">{{ list_sp.number }}</a></li>

                    {% if list_sp.has_next %}

                    <li><a href="?page={{ list_sp.next_page_number }}">{{ list_sp.next_page_number }}</a></li>
                    {% endif %} {% if list_sp.has_next %}
                    <li>
                      <a href="?page={{ list_sp.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </nav>
              </div>
            </div>
          </div>
          <!-- <div class="related-products-wrapper">
            <h2 class="related-products-title">Related Products</h2>
            <div class="related-products-carousel">
              <div class="single-product">
                <div class="product-f-image">
                  <img src="img/product-1.jpg" alt="" />
                  <div class="product-hover">
                    <a href="" class="add-to-cart-link"
                      ><i class="fa fa-shopping-cart"></i> Add to cart</a
                    >
                    <a href="" class="view-details-link"
                      ><i class="fa fa-link"></i> See details</a
                    >
                  </div>
                </div>

                <h2><a href="">Sony Smart TV - 2015</a></h2>

                <div class="product-carousel-price">
                  <ins>$700.00</ins> <del>$800.00</del>
                </div>
              </div>
              <div class="single-product">
                <div class="product-f-image">
                  <img src="img/product-2.jpg" alt="" />
                  <div class="product-hover">
                    <a href="" class="add-to-cart-link"
                      ><i class="fa fa-shopping-cart"></i> Add to cart</a
                    >
                    <a href="" class="view-details-link"
                      ><i class="fa fa-link"></i> See details</a
                    >
                  </div>
                </div>

                <h2><a href="">Apple new mac book 2015 March :P</a></h2>
                <div class="product-carousel-price">
                  <ins>$899.00</ins> <del>$999.00</del>
                </div>
              </div>
              <div class="single-product">
                <div class="product-f-image">
                  <img src="img/product-3.jpg" alt="" />
                  <div class="product-hover">
                    <a href="" class="add-to-cart-link"
                      ><i class="fa fa-shopping-cart"></i> Add to cart</a
                    >
                    <a href="" class="view-details-link"
                      ><i class="fa fa-link"></i> See details</a
                    >
                  </div>
                </div>

                <h2><a href="">Apple new i phone 6</a></h2>

                <div class="product-carousel-price">
                  <ins>$400.00</ins> <del>$425.00</del>
                </div>
              </div>
              <div class="single-product">
                <div class="product-f-image">
                  <img src="img/product-4.jpg" alt="" />
                  <div class="product-hover">
                    <a href="" class="add-to-cart-link"
                      ><i class="fa fa-shopping-cart"></i> Add to cart</a
                    >
                    <a href="" class="view-details-link"
                      ><i class="fa fa-link"></i> See details</a
                    >
                  </div>
                </div>

                <h2><a href="">Sony playstation microsoft</a></h2>

                <div class="product-carousel-price">
                  <ins>$200.00</ins> <del>$225.00</del>
                </div>
              </div>
              <div class="single-product">
                <div class="product-f-image">
                  <img src="img/product-5.jpg" alt="" />
                  <div class="product-hover">
                    <a href="" class="add-to-cart-link"
                      ><i class="fa fa-shopping-cart"></i> Add to cart</a
                    >
                    <a href="" class="view-details-link"
                      ><i class="fa fa-link"></i> See details</a
                    >
                  </div>
                </div>

                <h2><a href="">Sony Smart Air Condtion</a></h2>

                <div class="product-carousel-price">
                  <ins>$1200.00</ins> <del>$1355.00</del>
                </div>
              </div>
              <div class="single-product">
                <div class="product-f-image">
                  <img src="img/product-6.jpg" alt="" />
                  <div class="product-hover">
                    <a href="" class="add-to-cart-link"
                      ><i class="fa fa-shopping-cart"></i> Add to cart</a
                    >
                    <a href="" class="view-details-link"
                      ><i class="fa fa-link"></i> See details</a
                    >
                  </div>
                </div>

                <h2><a href="">Samsung gallaxy note 4</a></h2>

                <div class="product-carousel-price">
                  <ins>$400.00</ins>
                </div>
              </div>
            </div>
          </div> -->
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

WebBH/templates/store/history.html
{% extends 'store/base.html'%} {% load static%} {% load humanize %} {% block contentblock%}
<div class="product-big-title-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="product-bit-title text-center">
          <h2>Lịch sử giao dịch</h2>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="single-product-area">
  <div class="zigzag-bottom"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="product-content-right">
          <div class="woocommerce">
            {% if listorder %}

            <table cellspacing="0" class="shop_table cart">
              <thead>
                <tr>
                  <th class="product-name">Mã Đơn hàng</th>
                  <th class="product-price">Trạng thái</th>
                  <th class="product-quantity">Ngày tạo</th>
                  <th class="product-subtotal">Tổng tiền</th>
                </tr>
              </thead>
              <tbody>
                <!-- item -->

                {% for item in listorder %}
                <tr class="cart_item">
                  <td class="product-price">
                    {% if item.trangthai == True %}
                    <a href="{% url 'donhangs:chitiet' item.id %}"><span class="amount">{{item.id}}</span></a>
                    {%else%}
                    <a href="{% url 'donhangs:view_cart' %}"><span class="amount">{{item.id}}</span></a>
                    {%endif%}
                  </td>

                  <td class="product-price">
                    <span class="amount"
                      >{% if item.trangthai == True %} Đã thanh toán {%else%} Chưa thanh toán {%endif%}</span
                    >
                  </td>

                  <td class="product-subtotal">
                    <span class="amount">{{item.ngaydat}}</span>
                  </td>

                  <td class="product-subtotal">
                    <span class="amount">{{item.tongtien|intcomma}} VNĐ</span>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>

            {% else %}
            <h2 style="text-align: center">Không có đơn hàng</h2>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

WebBH/templates/store/shop.html
{% extends 'store/base.html'%} {% load static%} {% load humanize %} {% block contentblock%}
<div class="mainmenu-area">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'sanpham:home' %}">Home</a></li>
          <li class="active">
            <a href="{% url 'sanpham:shop_page' %}">Sản phẩm</a>
          </li>
          <!-- <li><a href="single-product.html">Single product</a></li> -->
          <li><a href="{% url 'sanpham:category' %}">Thể loại</a></li>

          <!-- <li><a href="#">Others</a></li> -->
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="product-big-title-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="product-bit-title text-center">
          <h2>Shop</h2>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="single-product-area">
  <div class="zigzag-bottom"></div>
  <div class="container">
    <div class="row">
      {% for item in list_sp %}
      <div class="col-md-3 col-sm-6">
        <div class="single-shop-product" style="position: relative; height: 400px">
          <div class="product-upper" style="height: 270px; position: relative">
            <img
              src="{% static item.hinhanh %}"
              alt=""
              style="position: absolute; top: 50%; transform: translateY(-50%)"
            />
          </div>
          <h2>
            <a style="text-transform: uppercase" href="{% url 'sanpham:detail_product' item.id_sanpham %}"
              >{{item.tensanpham}}</a
            >
          </h2>
          <div class="product-carousel-price" style="position: absolute; bottom: 12%">
            <ins>{{item.dongia| intcomma}} VNĐ</ins>
            <!-- <del>$999.00</del> -->
          </div>

          <div class="product-option-shop" style="position: absolute; bottom: 0%">
            <a
              class="add_to_cart_button"
              data-quantity="1"
              data-product_sku=""
              data-product_id="70"
              rel="nofollow"
              href="{% url 'donhangs:add_cart' item.id_sanpham %}"
              >Add to cart</a
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="product-pagination text-center">
          <nav>
            <ul class="pagination">
              {% if list_sp.has_previous %}
              <li>
                <a href="?page={{ list_sp.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li><a href="?page={{ list_sp.previous_page_number }}">{{ list_sp.previous_page_number }}</a></li>

              {% endif %}
              <li><a href="?page={{ list_sp.number }}">{{ list_sp.number }}</a></li>

              {% if list_sp.has_next %}

              <li><a href="?page={{ list_sp.next_page_number }}">{{ list_sp.next_page_number }}</a></li>
              {% endif %} {% if list_sp.has_next %}
              <li>
                <a href="?page={{ list_sp.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}